# Generated by Django 5.1.4 on 2025-01-10 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="tutle",
            new_name="title",
        ),
    ]
